version: "3"
services:
  ocaml:
    build: .
    image: marionebl/ocaml-from-the-very-beginning-dev
    ports:
      - "8443:8443"
    volumes:
      - ".:/repo/"
    command: code-server --allow-http --no-auth /repo
